/**
 * Packs de palavras em Português de Portugal (pt-PT).
 * Mesmos slugs que os packs es-ES para o frontend mapear por locale.
 */

const curatedWordPacksPtPT = [
  {
    name: 'Cinema e Séries',
    slug: 'cine-series',
    description: 'Filmes, séries, atores e personagens famosos',
    tags: ['entretenimento', 'filmes', 'séries'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Harry Potter', 'Star Wars', 'O Padrinho', 'Titanic', 'Avatar',
      'Breaking Bad', 'Game of Thrones', 'Friends', 'Stranger Things', 'The Office',
      'Marvel', 'DC Comics', 'Disney', 'Pixar', 'Netflix',
      'Spider-Man', 'Batman', 'Iron Man', 'Joker', 'Thanos',
      'James Bond', 'Indiana Jones', 'Terminator', 'Matrix', 'Parque Jurássico',
      'Leonardo DiCaprio', 'Brad Pitt', 'Tom Cruise', 'Will Smith', 'Scarlett Johansson',
      'La Casa de Papel', 'Narcos', 'Lost', 'The Walking Dead', 'Vikings',
      'O Senhor dos Anéis', 'Hobbit', 'Toy Story', 'Frozen', 'Os Simpson',
      'Dune', 'Interstellar', 'Inception', 'Gladiador', 'Forrest Gump',
      'Pulp Fiction', 'Kill Bill', 'Django', 'Inglourious Basterds', 'Reservoir Dogs',
      'The Godfather', 'Scarface', 'Goodfellas', 'The Departed', 'Heat',
      'Black Mirror', 'Westworld', 'The Crown', 'Bridgerton', 'Squid Game',
      'Peaky Blinders', 'Ozark', 'Money Heist', 'Dark', 'The Witcher',
      'Aquaman', 'Wonder Woman', 'Superman', 'Flash', 'Green Lantern',
      'Captain America', 'Thor', 'Hulk', 'Black Widow', 'Doctor Strange',
      'Avengers', 'Guardians of the Galaxy', 'Black Panther', 'Ant-Man', 'Deadpool',
      'Shrek', 'Finding Nemo', 'O Rei Leão', 'Aladdin', 'Mulan',
      'Coco', 'Encanto', 'Moana', 'Zootopia', 'Inside Out',
      'Dwayne Johnson', 'Ryan Reynolds', 'Chris Hemsworth', 'Robert Downey Jr', 'Chris Evans',
      'Jennifer Lawrence', 'Emma Stone', 'Margot Robbie', 'Gal Gadot', 'Zendaya',
      'Christopher Nolan', 'Steven Spielberg', 'Quentin Tarantino', 'Martin Scorsese', 'Ridley Scott',
      'Óscar', 'Cannes', 'Emmy', 'Golden Globe', 'BAFTA',
      'Cinema de terror', 'Comédia romântica', 'Ficção científica', 'Documentário', 'Animação',
    ],
  },
  {
    name: 'Desporto',
    slug: 'deportes',
    description: 'Desportos, equipas, jogadores e competições',
    tags: ['desporto', 'futebol', 'basquetebol'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Futebol', 'Basquetebol', 'Ténis', 'Natação', 'Ciclismo',
      'Real Madrid', 'Barcelona', 'Manchester United', 'Juventus', 'Bayern Munich',
      'Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Mbappé', 'Ronaldinho',
      'NBA', 'NFL', 'FIFA', 'Champions League', 'Mundial',
      'Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Stephen Curry', 'Shaq',
      'Rafael Nadal', 'Roger Federer', 'Novak Djokovic', 'Serena Williams', 'Naomi Osaka',
      'Maradona', 'Pelé', 'Zinedine Zidane', 'David Beckham', 'Ronaldo Nazário',
      'Jogos Olímpicos', 'Tour de France', 'Super Bowl', 'Wimbledon', 'Roland Garros',
      'Golfe', 'Boxe', 'UFC', 'Fórmula 1', 'MotoGP',
      'Atletismo', 'Maratona', 'Salto em comprimento', 'Lançamento do dardo', 'Decatlo',
      'Liverpool', 'Chelsea', 'Arsenal', 'Manchester City', 'Tottenham',
      'Atlético de Madrid', 'Sevilla', 'Villarreal', 'Betis', 'Valência',
      'Luka Modric', 'Karim Benzema', 'Vinicius Jr', 'Haaland', 'Salah',
      'Kevin Durant', 'Giannis Antetokounmpo', 'Luka Doncic', 'Jayson Tatum', 'Nikola Jokic',
      'Carlos Alcaraz', 'Carlos Sainz', 'Fernando Alonso', 'Max Verstappen', 'Lewis Hamilton',
      'MMA', 'Kickboxing', 'Judo', 'Taekwondo', 'Luta livre',
      'Voleibol', 'Andebol', 'Rugby', 'Hóquei no gelo', 'Basebol',
      'Surf', 'Skate', 'Escalada', 'Paraquedismo', 'Mergulho',
      'Ginástica', 'Patinação artística', 'Esqui', 'Snowboard', 'Motocross',
    ],
  },
  {
    name: 'Viagens e Lugares',
    slug: 'viajes-lugares',
    description: 'Cidades, países, monumentos e destinos turísticos',
    tags: ['viagens', 'geografia', 'turismo'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Paris', 'Londres', 'Nova Iorque', 'Tóquio', 'Roma',
      'Torre Eiffel', 'Big Ben', 'Estátua da Liberdade', 'Coliseu', 'Taj Mahal',
      'Espanha', 'França', 'Itália', 'Japão', 'Estados Unidos',
      'Praia', 'Montanha', 'Deserto', 'Selva', 'Neve',
      'Barcelona', 'Madrid', 'Sevilha', 'Valência', 'Bilbau',
      'México', 'Argentina', 'Brasil', 'Chile', 'Colômbia',
      'Machu Picchu', 'Chichen Itzá', 'Cristo Redentor', 'Iguaçu', 'Patagónia',
      'Dubai', 'Maldivas', 'Bali', 'Tailândia', 'Grécia',
      'Pirâmides do Egipto', 'Grande Muralha da China', 'Petra', 'Angkor Wat', 'Stonehenge',
      'Berlim', 'Amesterdão', 'Lisboa', 'Praga', 'Viena',
      'Sydney', 'Melbourne', 'Toronto', 'Vancouver', 'Montreal',
      'São Francisco', 'Los Angeles', 'Miami', 'Chicago', 'Las Vegas',
      'Santorini', 'Mykonos', 'Creta', 'Capri', 'Amalfi',
      'Islândia', 'Noruega', 'Suécia', 'Finlândia', 'Dinamarca',
      'Portugal', 'Alemanha', 'Reino Unido', 'Irlanda', 'Suíça',
      'Egipto', 'Marrocos', 'África do Sul', 'Quénia', 'Tanzânia',
      'Índia', 'Vietname', 'Camboja', 'Sri Lanka', 'Nepal',
      'Alpes', 'Himalaias', 'Andes', 'Rocky Mountains', 'Grand Canyon',
      'Sagrada Família', 'Notre Dame', 'Acrópole', 'Alhambra', 'Neuschwanstein',
      'Caraíbas', 'Polinésia', 'Seicheles', 'Maurícia', 'Fiji',
    ],
  },
  {
    name: 'Comida e Bebida',
    slug: 'comida-bebida',
    description: 'Pratos, bebidas, sobremesas e gastronomia',
    tags: ['comida', 'gastronomia', 'bebidas'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Pizza', 'Hambúrguer', 'Sushi', 'Tacos', 'Massa',
      'Gelado', 'Chocolate', 'Bolo', 'Bolachas', 'Tarte',
      'Café', 'Chá', 'Coca-Cola', 'Cerveja', 'Vinho',
      'Paella', 'Tortilha espanhola', 'Presunto ibérico', 'Gazpacho', 'Churros',
      'Ramen', 'Poke Bowl', 'Burrito', 'Enchiladas', 'Ceviche',
      'Croissant', 'Baguete', 'Macaron', 'Crepe', 'Fondue',
      'Risotto', 'Tiramisu', 'Lasanha', 'Carbonara', 'Bolonhesa',
      'Empadas', 'Churrasco', 'Choripán', 'Milanesa', 'Alfajores',
      'Expresso', 'Cappuccino', 'Latte', 'Mojito', 'Margarita',
      'Tapas', 'Petiscos', 'Tortilha de batata', 'Salmorejo', 'Fabada',
      'Cozido', 'Tripas', 'Polvo à galega', 'Bacalhau', 'Gambas ao alho',
      'Tortilha', 'Quesadilha', 'Guacamole', 'Nachos', 'Tamales',
      'Caril', 'Pad Thai', 'Pho', 'Dim sum', 'Tempura',
      'Falafel', 'Hummus', 'Shawarma', 'Kebab', 'Baklava',
      'Fish and chips', 'Sunday roast', 'Full English', 'Haggis', 'Crumpets',
      'Bratwurst', 'Pretzel', 'Schnitzel', 'Chucrute', 'Strudel',
      'Gelato', 'Cannoli', 'Panna cotta', 'Bruschetta', 'Caprese',
      'Gin Tónico', 'Aperol Spritz', 'Sangria', 'Tinto de verão', 'Kalimotxo',
      'Whisky', 'Rum', 'Vodka', 'Gin', 'Tequila',
      'Água com gás', 'Sumo', 'Smoothie', 'Batido', 'Infusão',
      'Brownie', 'Cheesecake', 'Flan', 'Arroz doce', 'Rabanadas',
    ],
  },
  {
    name: 'Animais',
    slug: 'animales',
    description: 'Todo o tipo de animais do mundo',
    tags: ['animais', 'naturaleza', 'fauna'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Cão', 'Gato', 'Leão', 'Tigre', 'Elefante',
      'Girafa', 'Zebra', 'Hipopótamo', 'Rinoceronte', 'Gorila',
      'Golfinho', 'Baleia', 'Tubarão', 'Polvo', 'Pinguim',
      'Águia', 'Mocho', 'Papagaio', 'Flamingo', 'Beija-flor',
      'Cobra', 'Crocodilo', 'Tartaruga', 'Lagarto', 'Camaleão',
      'Urso polar', 'Panda', 'Coala', 'Canguru', 'Vombate',
      'Cavalo', 'Vaca', 'Porco', 'Ovelha', 'Galinha',
      'Borboleta', 'Abelha', 'Formiga', 'Aranha', 'Escaravelho',
      'Lobo', 'Raposa', 'Coelho', 'Esquilo', 'Guaxinim',
      'Hamster', 'Porquinho-da-índia', 'Rato', 'Furão', 'Ouriço',
      'Orca', 'Foca', 'Morsa', 'Manati', 'Lontra',
      'Peixe-palhaço', 'Cavalo-marinho', 'Alforreca', 'Estrela-do-mar', 'Ouriço-do-mar',
      'Caranguejo', 'Lagosta', 'Lula', 'Amêijoa', 'Ostra',
      'Pavão', 'Tucano', 'Arara', 'Corvo', 'Gaivota',
      'Morcego', 'Toupeira', 'Texugo', 'Doninha', 'Lontra',
      'Jaguar', 'Leopardo', 'Guepardo', 'Puma', 'Lince',
      'Macaco', 'Chimpanzé', 'Orangotango', 'Mandril', 'Lémure',
      'Hiena', 'Raposa do Ártico', 'Rena', 'Alce', 'Bisonte',
      'Cabra', 'Burro', 'Lhama', 'Alpaca', 'Yak',
      'Grilo', 'Gafanhoto', 'Louva-a-deus', 'Libélula', 'Joaninha',
      'Caracol', 'Lesma', 'Minhoca', 'Sanguessuga', 'Alforreca',
    ],
  },
  {
    name: 'Tecnologia',
    slug: 'tecnologia',
    description: 'Marcas, produtos e tecnologia moderna',
    tags: ['tecnologia', 'gadgets', 'marcas'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'iPhone', 'Samsung', 'Google', 'Apple', 'Microsoft',
      'PlayStation', 'Xbox', 'Nintendo', 'Switch', 'Steam',
      'Instagram', 'TikTok', 'YouTube', 'Twitter', 'Facebook',
      'WhatsApp', 'Telegram', 'Discord', 'Zoom', 'Spotify',
      'Netflix', 'Amazon', 'Tesla', 'SpaceX', 'NASA',
      'Inteligência Artificial', 'ChatGPT', 'Robot', 'Drone', 'VR',
      'Portátil', 'Tablet', 'Smartwatch', 'AirPods', 'Kindle',
      'WiFi', 'Bluetooth', 'USB', 'HDMI', 'SSD',
      'Uber', 'Airbnb', 'PayPal', 'Stripe', 'Bitcoin',
      'Android', 'iOS', 'Windows', 'macOS', 'Linux',
      'LinkedIn', 'Pinterest', 'Snapchat', 'Twitch', 'Reddit',
      'GitHub', 'GitLab', 'Slack', 'Notion', 'Trello',
      'Ethereum', 'Criptomoeda', 'NFT', 'Blockchain', 'Metaverso',
      'Alexa', 'Siri', 'Google Assistant', 'Cortana', 'Bixby',
      'Chromecast', 'Fire TV', 'Apple TV', 'Roku', 'Smart TV',
      'GoPro', 'Drone DJI', 'Oculus', 'Meta Quest', 'PSVR',
      'Canon', 'Nikon', 'Sony', 'GoPro', 'Insta360',
      '5G', 'Fibra ótica', 'Cloud', 'VPN', 'Firewall',
      'Código QR', 'NFC', 'Carregador sem fios', 'Power bank', 'Hub USB',
    ],
  },
  {
    name: 'Música',
    slug: 'musica',
    description: 'Artistas, géneros e música',
    tags: ['música', 'artistas', 'géneros'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Rock', 'Pop', 'Reggaeton', 'Hip Hop', 'Jazz',
      'The Beatles', 'Queen', 'Michael Jackson', 'Madonna', 'Elvis Presley',
      'Bad Bunny', 'Shakira', 'Rosalía', 'J Balvin', 'Daddy Yankee',
      'Taylor Swift', 'Beyoncé', 'Ariana Grande', 'Ed Sheeran', 'Drake',
      'Guitarra', 'Piano', 'Bateria', 'Baixo', 'Violino',
      'Spotify', 'YouTube Music', 'Apple Music', 'SoundCloud', 'Deezer',
      'Reggae', 'Salsa', 'Bachata', 'Cumbia', 'Tango',
      'Coldplay', 'Imagine Dragons', 'Maroon 5', 'One Direction', 'BTS',
      'Karaoke', 'Concerto', 'Festival', 'DJ', 'Rap',
      'Freddie Mercury', 'David Bowie', 'Prince', 'Whitney Houston', 'Amy Winehouse',
      'AC/DC', 'Led Zeppelin', 'Pink Floyd', 'Nirvana', 'Metallica',
      'U2', 'Radiohead', 'Oasis', 'Blur', 'Arctic Monkeys',
      'Saxofone', 'Trompete', 'Trombone', 'Flauta', 'Clarinete',
      'Ópera', 'Clássica', 'Sinfónica', 'Fado', 'Folk',
      'Billboard', 'Grammy', 'MTV', 'Eurovisão', 'San Remo',
      'Vinil', 'CD', 'Cassete', 'Streaming', 'Playlist',
      'Rauw Alejandro', 'Karol G', 'Anuel', 'Ozuna', 'Maluma',
      'Harry Styles', 'Billie Eilish', 'Dua Lipa', 'The Weeknd', 'Bruno Mars',
    ],
  },
  {
    name: 'Profissões',
    slug: 'profesiones',
    description: 'Profissões e ofícios',
    tags: ['profissões', 'trabalhos', 'ofícios'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Médico', 'Enfermeiro', 'Professor', 'Engenheiro', 'Arquiteto',
      'Advogado', 'Polícia', 'Bombeiro', 'Chef', 'Empregado de mesa',
      'Piloto', 'Comissário de bordo', 'Taxista', 'Condutor', 'Mecânico',
      'Eletricista', 'Canalizador', 'Carpinteiro', 'Pintor', 'Pedreiro',
      'Programador', 'Designer', 'Fotógrafo', 'Jornalista', 'Escritor',
      'Ator', 'Cantor', 'Músico', 'Bailarino', 'Realizador',
      'Veterinário', 'Dentista', 'Farmacêutico', 'Psicólogo', 'Fisioterapeuta',
      'Banqueiro', 'Contabilista', 'Economista', 'Empresário', 'Vendedor',
      'Agricultor', 'Pecuário', 'Pescador', 'Mineiro', 'Silvicultor',
      'Juiz', 'Procurador', 'Notário', 'Secretário', 'Administrativo',
      'Comercial', 'Marketing', 'Recursos Humanos', 'Compras', 'Logística',
      'Investigador', 'Científico', 'Biólogo', 'Químico', 'Físico',
      'Tradutor', 'Intérprete', 'Guia turístico', 'Rececionista', 'Porteiro',
      'Treinador', 'Árbitro', 'Atleta', 'Massagista', 'Nutricionista',
      'Cabeleireiro', 'Esteticista', 'Barbeiro', 'Manicure', 'Maquilhador',
      'Militar', 'Guarda', 'Segurança', 'Vigilante',
      'Astronauta', 'Paleontólogo', 'Arqueólogo', 'Historiador', 'Geólogo',
      'Compositor', 'Produtor', 'DJ', 'Crítico', 'Editor',
    ],
  },
  {
    name: 'Natureza e Clima',
    slug: 'naturaleza-clima',
    description: 'Elementos naturais, fenómenos e clima',
    tags: ['naturaleza', 'clima', 'ambiente'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Sol', 'Lua', 'Estrela', 'Nuvem', 'Chuva',
      'Neve', 'Vento', 'Tempestade', 'Raio', 'Trovão',
      'Aurora boreal', 'Arco-íris', 'Nevoeiro', 'Granizo', 'Ventania',
      'Floresta', 'Rio', 'Lago', 'Oceano', 'Cascata',
      'Vulcão', 'Sismo', 'Tsunami', 'Furacão', 'Tornado',
      'Praia', 'Penhasco', 'Ilha', 'Península', 'Baía',
      'Deserto', 'Oásis', 'Dunas', 'Cato', 'Palmeira',
      'Montanha', 'Vale', 'Colina', 'Desfiladeiro', 'Gruta',
      'Selva', 'Jungla', 'Savana', 'Tundra', 'Pradaria',
      'Árvore', 'Flor', 'Relva', 'Musgo', 'Feto',
      'Rosa', 'Girassol', 'Tulipa', 'Margarida', 'Orquídea',
      'Carvalho', 'Pinheiro', 'Oliveira', 'Cipreste', 'Salgueiro',
      'Primavera', 'Verão', 'Outono', 'Inverno', 'Estação',
      'Amanhecer', 'Anoitecer', 'Eclipse', 'Maré', 'Onda',
      'Poluição', 'Reciclagem', 'Energia solar', 'Eólica', 'Sustentável',
    ],
  },
  {
    name: 'Ciência',
    slug: 'ciencia',
    description: 'Ciência, espaço e descobertas',
    tags: ['ciência', 'espaço', 'investigação'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Átomo', 'Molécula', 'ADN', 'Gene', 'Célula',
      'Gravidade', 'Relatividade', 'Buraco negro', 'Galáxia', 'Planeta',
      'Terra', 'Marte', 'Júpiter', 'Saturno', 'Lua',
      'Estação Espacial', 'Foguete', 'Satélite', 'Telescópio', 'Microscópio',
      'Einstein', 'Newton', 'Hawking', 'Darwin', 'Marie Curie',
      'Física', 'Química', 'Biologia', 'Matemáticas', 'Astronomia',
      'Equação', 'Teoria', 'Experiência', 'Hipótese', 'Laboratório',
      'Vacina', 'Antibiótico', 'Vírus', 'Bactéria', 'Imunidade',
      'Energia', 'Eletricidade', 'Magnetismo', 'Luz', 'Som',
      'Evolução', 'Extinção', 'Fóssil', 'Dinossauro', 'Ecossistema',
      'Clonagem', 'Edição genética', 'CRISPR', 'Robótica', 'Nanotecnologia',
      'Big Bang', 'Universo', 'Via Láctea', 'Nebulosa', 'Supernova',
      'Oceano', 'Fundo marinho', 'Coral', 'Plâncton', 'Biodiversidade',
      'Alterações climáticas', 'Efeito de estufa', 'Renovável', 'Nuclear', 'Fusão',
    ],
  },
  {
    name: 'História',
    slug: 'historia',
    description: 'Épocas, personagens e eventos históricos',
    tags: ['história', 'civilização', 'cultura'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Antigo Egipto', 'Império Romano', 'Grécia clássica', 'Idade Média', 'Renascimento',
      'Revolução Francesa', 'Revolução Industrial', 'Guerras Mundiais', 'Guerra Fria', 'Queda do Muro',
      'Cleópatra', 'Júlio César', 'Alexandre Magno', 'Napoleão', 'Gengis Khan',
      'Cristóvão Colombo', 'Descobrimento da América', 'Conquistadores', 'Inca', 'Asteca',
      'Reis Católicos', 'Filipe II', 'Carlos V', 'Isabel a Católica', 'Fernando de Aragão',
      'Pirâmides', 'Coliseu', 'Partenon', 'Acrópole', 'Stonehenge',
      'Vikings', 'Cavaleiros', 'Castelos', 'Catedrais', 'Cruzadas',
      'Império Bizantino', 'Império Otomano', 'Dinastia Ming', 'Samurais', 'Xogum',
      'Revolução Russa', 'Gandhi', 'Martin Luther King', 'Nelson Mandela', 'Churchill',
      'Paleolítico', 'Neolítico', 'Idade do Bronze', 'Idade do Ferro', 'Antiguidade',
      'Piratas', 'Corsários', 'Bucaneiros', 'Armada Invencível', 'Titanic',
      'Reforma', 'Contrarreforma', 'Iluminismo', 'Revolução', 'Independência',
      'Arqueologia', 'Manuscritos', 'Pergaminhos', 'Hieróglifos', 'Papiros',
    ],
  },
  {
    name: 'Arte e Cultura',
    slug: 'arte-cultura',
    description: 'Pintura, escultura, literatura e arte',
    tags: ['arte', 'cultura', 'literatura'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Mona Lisa', 'Guernica', 'Noite estrelada', 'O Grito', 'Criação de Adão',
      'Picasso', 'Dalí', 'Velázquez', 'Goya', 'Miguel Ângelo',
      'Van Gogh', 'Monet', 'Rembrandt', 'Da Vinci', 'Rafael',
      'Museu do Prado', 'Louvre', 'MOMA', 'Tate', 'Reina Sofía',
      'Escultura', 'Pintura', 'Gravura', 'Aguarela', 'Óleo',
      'Cervantes', 'D. Quixote', 'García Márquez', 'Borges', 'Pablo Neruda',
      'Shakespeare', 'Homero', 'Dante', 'Orwell', 'Kafka',
      'Teatro', 'Ópera', 'Ballet', 'Dança', 'Performance',
      'Fotografia', 'Cinema', 'Documentário', 'Curta-metragem', 'Animação',
      'Arquitetura gótica', 'Barroco', 'Modernismo', 'Minimalismo', 'Surrealismo',
      'Grafitti', 'Street art', 'Mural', 'Instalação', 'Arte digital',
      'Poesia', 'Romance', 'Ensaio', 'Conto', 'Banda desenhada',
      'Guggenheim', 'Sagrada Família', 'Torre de Pisa', 'Cristo Redentor', 'Estátua da Liberdade',
    ],
  },
  {
    name: 'Moda',
    slug: 'moda',
    description: 'Roupa, acessórios e tendências',
    tags: ['moda', 'roupa', 'estilo'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Calças de ganga', 'T-shirt', 'Vestido', 'Casaco', 'Casaco de inverno',
      'Sapatilhas', 'Botas', 'Sandálias', 'Sapatos de salto', 'Mocassins',
      'Boné', 'Chapéu', 'Cachecol', 'Luvas', 'Cinto',
      'Mala', 'Mochila', 'Carteira', 'Relógio', 'Óculos de sol',
      'Chanel', 'Gucci', 'Louis Vuitton', 'Prada', 'Hermès',
      'Nike', 'Adidas', 'Zara', 'H&M', 'Uniqlo',
      'Alta costura', 'Prêt-à-porter', 'Streetwear', 'Vintage', 'Segunda mão',
      'Passerelle', 'Fashion Week', 'Editorial', 'Influencer', 'Trend',
      'Alfaiataria', 'Ganga', 'Couro', 'Seda', 'Lã',
      'Minimalista', 'Boémio', 'Clássico', 'Desportivo', 'Glamour',
      'Biquíni', 'Fato de banho', 'Sweat', 'Leggings', 'Blazer',
      'Brincos', 'Colar', 'Pulseira', 'Anel', 'Broche',
      'Maquilhagem', 'Skincare', 'Perfume', 'Unhas', 'Penteado',
    ],
  },
  {
    name: 'Videojogos',
    slug: 'videojuegos',
    description: 'Jogos, consolas e personagens',
    tags: ['videojogos', 'gaming', 'consolas'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Mario', 'Zelda', 'Pokémon', 'Minecraft', 'Fortnite',
      'FIFA', 'Call of Duty', 'GTA', 'The Last of Us', 'Elden Ring',
      'PlayStation', 'Xbox', 'Nintendo Switch', 'PC Gaming', 'Steam',
      'Super Smash Bros', 'Mario Kart', 'Animal Crossing', 'Splatoon', 'Metroid',
      'League of Legends', 'Valorant', 'Overwatch', 'Dota', 'Counter-Strike',
      'World of Warcraft', 'Final Fantasy', 'Dark Souls', 'Bloodborne', 'Sekiro',
      "Assassin's Creed", 'God of War', 'Uncharted', 'Horizon', 'Spider-Man',
      'Pikachu', 'Link', 'Donkey Kong', 'Kirby', 'Samus',
      'Streamer', 'Twitch', 'eSports', 'Torneio', 'Ranked',
      'RPG', 'FPS', 'MMO', 'Battle Royale', 'Sandbox',
      'Retro', 'Arcada', 'Indie', 'AAA', 'DLC',
      'Resident Evil', 'Silent Hill', 'Dead Space', 'Outlast', 'Five Nights',
      'Halo', 'Gears of War', 'Forza', 'Sea of Thieves', 'Minecraft',
    ],
  },
  {
    name: 'Casa',
    slug: 'hogar',
    description: 'Móveis, objetos e vida em casa',
    tags: ['casa', 'decoração', 'móveis'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Sofá', 'Cama', 'Mesa', 'Cadeira', 'Armário',
      'Secretária', 'Estante', 'Candeeiro', 'Espelho', 'Quadro',
      'Cozinha', 'Frigorífico', 'Forno', 'Lava-louça', 'Micro-ondas',
      'Casa de banho', 'Ducha', 'Lavatório', 'Sanita', 'Banheira',
      'Jardim', 'Terraço', 'Varanda', 'Garagem', 'Cave',
      'Almofada', 'Manta', 'Lençóis', 'Edredão', 'Colchão',
      'Cortinas', 'Persianas', 'Alcatifa', 'Tapete', 'Almofada de sofá',
      'Planta', 'Vaso', 'Jarro', 'Velas', 'Ambientador',
      'Ferramentas', 'Berbequim', 'Martelo', 'Chave de fendas', 'Chave inglesa',
      'Aspirador', 'Esfregona', 'Vassoura', 'Balde', 'Pano',
      'Máquina de lavar', 'Secador', 'Ferro', 'Secador de cabelo', 'Ventilador',
      'Televisão', 'Comando', 'Coluna', 'Router', 'Tomada',
      'Livro', 'Revista', 'Jornal', 'Caderno', 'Lápis',
    ],
  },
  {
    name: 'Transportes',
    slug: 'transporte',
    description: 'Veículos e meios de transporte',
    tags: ['transportes', 'veículos', 'viagens'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Carro', 'Mota', 'Bicicleta', 'Autocarro', 'Metro',
      'Comboio', 'Avião', 'Barco', 'Ferry', 'Helicóptero',
      'Táxi', 'Uber', 'Cabify', 'Carsharing', 'Trotinete',
      'Camião', 'Furgão', 'Ambulância', 'Polícia', 'Bombeiros',
      'Fórmula 1', 'NASCAR', 'Rali', 'Kart', 'Buggy',
      'Iate', 'Veleiro', 'Caiaque', 'Canoa', 'Submarino',
      'Aeroporto', 'Estação', 'Porto', 'Parque de estacionamento', 'Bomba de gasolina',
      'Passaporte', 'Bilhete', 'Bagagem', 'Mala', 'Mochila',
      'Semaforo', 'Rotunda', 'Autoestrada', 'Estrada', 'Portagem',
      'Condutor', 'Copiloto', 'Passageiro', 'Comissário de bordo', 'Piloto',
      'Roda', 'Motor', 'Travões', 'Óleo', 'Gasolina',
      'Tesla', 'BMW', 'Mercedes', 'Audi', 'Volkswagen',
    ],
  },
  {
    name: 'Saúde e Corpo',
    slug: 'salud-cuerpo',
    description: 'Saúde, desporto pessoal e bem-estar',
    tags: ['saúde', 'bem-estar', 'corpo'],
    isAdult: false,
    locale: 'pt-PT',
    words: [
      'Ginásio', 'Correr', 'Yoga', 'Pilates', 'CrossFit',
      'Meditação', 'Mindfulness', 'Respiração', 'Relaxamento', 'Spa',
      'Dieta', 'Nutrição', 'Proteína', 'Vitaminas', 'Suplementos',
      'Dormir', 'Descanso', 'Insónia', 'Sono', 'Despertador',
      'Dor de cabeça', 'Gripe', 'Constipação', 'Febre', 'Tosse',
      'Coração', 'Pulmões', 'Fígado', 'Rim', 'Cérebro',
      'Ossos', 'Músculos', 'Pele', 'Cabelo', 'Unhas',
      'Dentista', 'Oftalmologista', 'Cardiologista', 'Dermatologista', 'Ortopedista',
      'Radiografia', 'Análise ao sangue', 'Ecografia', 'TAC', 'Ressonância',
      'Fisioterapia', 'Reabilitação', 'Massagem', 'Osteopatia', 'Acupuntura',
      'Alergia', 'Asma', 'Diabetes', 'Tensão arterial', 'Colesterol',
      'Higiene', 'Lavar as mãos', 'Escova de dentes', 'Fio dental', 'Desodorizante',
    ],
  },
  {
    name: 'Adultos',
    slug: 'adultos',
    description: 'Conteúdo para maiores de 18 anos',
    tags: ['adultos', '+18', 'picante'],
    isAdult: true,
    locale: 'pt-PT',
    words: [
      'Tinder', 'OnlyFans', 'Viagra', 'Kamasutra', 'Stripper',
      'Bachelor Party', 'Pole Dance', 'Jacuzzi', 'Massagem', 'Lingerie',
      'Romance', 'Encontro', 'Beijo', 'Conquista', 'Sedução',
      'Bar', 'Discoteca', 'Ressaca', 'Shot', 'Tequila',
      'Tatuagem', 'Piercing', 'Biquíni', 'Sauna', 'Spa',
      'Cocktail', 'Vodka', 'Whisky', 'Cerveja', 'Vinho',
      'Festa', 'Afterwork', 'Karaoke', 'Pub', 'Nightclub',
    ],
  },
  {
    name: 'Modo Personalizado',
    slug: 'personalizado',
    description: 'Palavras adicionadas pelos utilizadores',
    tags: ['personalizado', 'custom'],
    isAdult: false,
    locale: 'pt-PT',
    words: [],
    isPremium: true,
  },
];

module.exports = { curatedWordPacksPtPT };
